### ISSUE TITLE
x264-libs Skipping packages with broken dependencies

### ISSUE THREAD

**Issue by sudhirkhanger** [negativo17/HandBrake#1]
```
$ sudo dnf update
Last metadata expiration check: 0:16:41 ago on Tue Jun 28 09:35:23 2016.
Dependencies resolved.
========================================================================================================================================================================
 Package                             Arch                             Version                                          Repository                                  Size
========================================================================================================================================================================
Skipping packages with broken dependencies:
 x264-libs                           x86_64                           1:0.148-4.fd2c324.fc24                           fedora-HandBrake                           588 k

Transaction Summary
========================================================================================================================================================================
Skip  1 Package

Nothing to do.
Complete!
```

**Comment by scaronni** [comment]
With this output there is no detail about what is causing this; so I can't help. I have it installed and have no dependency issues. Can you run this command? This will print what is causing the error.

`dnf --best update`

**Comment by sudhirkhanger** [comment]
Error: package x264-0.148-7.20160614gita5e06b9.fc24.x86_64 requires x264-libs(x86-64) = 0.148-7.20160614gita5e06b9.fc24, but none of the providers can be installed

**Comment by scaronni** [comment]
I was only planning to ship libraries and not the main encoder binary as all functions are in `ffmpeg` and it pulls in the whole `gpac` set of libraries. I've enabled the `x264` binaries to use dynamic `gpac`.

Are you using it instead of `ffmpeg` for converting videos? May I ask you why?

**Comment by sudhirkhanger** [comment]
I have no idea. I only installed Handbrake a long time ago and used it once. I don't understand it all.

**Comment by scaronni** [comment]
Ok, you can remove it, you just need the libs :)
