### ISSUE TITLE
Doesn't play well with duh gnome 3.20 copr

### ISSUE THREAD

**Issue by ghost** [negativo17/HandBrake#2]
Hi, so duh's gnome 3.20 copr that exists at https://copr.fedorainfracloud.org/coprs/duh/GNOME_3.20_for_RHEL_and_CentOS_7.x/

Conflicts with your dependancy packages. Mainly libsrtp and libwebp.

Maybe a compromise can be worked out ?

Cause it's causing a problem for me to use Spotify client on centos with both repos installed.

**Comment by scaronni** [comment]
For Spotify you don't need the multimedia repository to be available on the system. Just add the Spotify repository, the only dependency is compat-openssl which is in the repository as well:

http://negativo17.org/repos/spotify/epel-7/x86_64/

You only need some other FFMpeg libraries (< 3.1) only if you want to play local files.

That "duh" repository also overwrite packages from the base distribution. I can't track every possible repository that is on the web and try to make things work, sorry.

**Comment by ghost** [comment]
Makes sense... But ffmpeg is not an optional dependancy ... So it leads to issues when installing with yum(and no handbrake being present)

**Comment by ghost** [comment]
Maybe .... That could be worked out ?

**Comment by scaronni** [comment]
Actually the dependency should be `compat-ffmpeg-libs` and not `ffmpeg-libs`, that's a mistake on my side, but that does not solve your problem.

Will make the dependency optional through a weak dependency, it's only required for playing local files. For now, you can just download and install the package manually through `rpm -i --nodeps compat-openssl*.rpm spotify-client*.rpm`

**Comment by ghost** [comment]
I know but I love yum.anyways thanks for your help.

**Comment by scaronni** [comment]
It's now optional on the new 64 bit build:

https://github.com/negativo17/spotify-client/commit/ec451b77e5a1411b0bd8827fa4ef90abb299609b

On fedora it's suggested, on CentOS not.
